### ISSUE TITLE
No music in Deathkings of the Dark Citadel

### ISSUE THREAD

**Issue by LOL-DUDE-64** [Lemon-King/HXDD#1]
More detailed information [here](https://doomwiki.org/wiki/Deathkings_music#Music_issues).
Granted, this is not an issue with HXDD specifically, but even if I put in the patched HEXDD.WAD, there's still no music in this episode.
Is there any way you could incorporate the patch into HXDD?

**Comment by Lemon-King** [comment]
Hey, I have resumed the project. HexDD is a currently supported but unfinished as far as gameplay goes and needs a preprocessor before its fully functional. Keeping open to track this in the long term.

**Comment by Lemon-King** [comment]
Added via https://github.com/Lemon-King/HXDD/commit/e135c62d41ab8e8c5359d94bb355d1b31f754262 https://github.com/Lemon-King/HXDD/commit/f46f7d88e1e22c3547588d0ae82ceceaa0f61dee

**Comment by Lemon-King** [comment]
Deathkings now is working in the latest commits.
