### ISSUE TITLE
Program hangs if Hexen and Deathkings WADs are selected, but not Heretic

### ISSUE THREAD

**Issue by LOL-DUDE-64** [Lemon-King/HXDD#4]
Specifically on [this screen.](https://github.com/Lemon-King/HXDD/assets/72108468/d3551f1d-a4d4-4313-94a2-1f78d89e1f2d) I'm assuming that merging just Hexen and Deathkings is not supported.
Could that be a consideration, though, for those who want to have just a full Hexen WAD without mixing Heretic in with it?

**Comment by Lemon-King** [comment]
Yes, it merges all and Hexen + Deathkings is not an option. It also shouldn't be possible to kick off the process without all the correct wads selected. But either way I'll look into that.

**Comment by Lemon-King** [comment]
Fixed with https://github.com/Lemon-King/HXDD/commit/0550243a45ad9eead5c9198b700220acfe471a65
