### ISSUE TITLE
Co-op support for multiple characters

### ISSUE THREAD

**Issue by kloon15** [Lemon-King/HXDD#5]
Loving the mod, and would love to play this w others, but if we wanna play different characters, the pickups are not universal, and only relevant for the host character, meaning for instance u wont get any ammo for other characters.
Would u be able to make ammo/item pickups be universal? So it converts it into whatever the equivalent would be for the character thats picking it up.
This issue is rectified in Walpurgis since every character uses only blue and green mana for ammo but sadly that mod makes the game hang on a blank screen on map load in multiplayer (strangely hexen is not affected but doom and heretic is a no-go) and dev is unable due to IRL stuff, so if u could help me out in either case that would be amazing!

**Comment by Lemon-King** [comment]
Universal / Shared pickups is something I want to add in the future for features. I'll be updating my topics on ZD and DW with future plans once 0.8.1 is out.

**Comment by Lemon-King** [comment]
Added in: https://github.com/Lemon-King/HXDD/commit/6fb0c7a31ea6c3a6cbeb2462ce86de0edab02e5c

**Comment by kloon15** [comment]
Thank you! A small bug, the items/ammo doesnt disappear upon pickup anymore.

**Comment by Lemon-King** [comment]
I've been doing local testing and haven't run across that yet. Were you running any mods alongside it?

**Comment by kloon15** [comment]
Nope just GZDoom 4.12.2 and latest artifact from [here](https://github.com/Lemon-King/HXDD/actions/runs/9707771473).
Using the following commands:
```
gzdoom.exe -host 2 -port 27666 -skill 4 +map E1M1 +playerclass Mage +hxdd_armor_mode 2 +hxdd_progression 2
gzdoom.exe -join 127.0.0.1 -port 27666 +playerclass Cleric
```

**Comment by kloon15** [comment]
And i couldnt pick up the armor in the first secret room, and neither this item:
![2024-06-28](https://github.com/Lemon-King/HXDD/assets/1431170/3ef7fa0e-1f87-41ec-9287-bfdd2b8ff85e)
