### ISSUE TITLE
Add support for widescreen assets from GZDoom.

### ISSUE THREAD

**Issue by Shockwave508** [Lemon-King/HXDD#6]
Seems that various UI elements such as intermission maps are still stuck in a 4:3 aspect ratio. This can be corrected by using the widescreen assets from GZDoom's game_widescreen_gfx.pk3.

**Comment by Lemon-King** [comment]
Thanks for noticing this. While game_widescreen_gfx those assets are not being converted. I'll ensure thats fixed in the next update.

**Comment by Lemon-King** [comment]
Added in: https://github.com/Lemon-King/HXDD/commit/73ead6a36c091c9a6eac3ebc689d68d8055100b8
