### ISSUE TITLE
Add option to disable/reduce HUD sway.

### ISSUE THREAD

**Issue by Shockwave508** [Lemon-King/HXDD#7]
I noticed that HXDD's built-in HUD bobs and sways relative to player and camera movement; would be nice to have an option to disable and/or reduce such movements and make the HUD remain still like any other GZDoom game.

**Comment by Lemon-King** [comment]
Feature added in: https://github.com/Lemon-King/HXDD/commit/fca83f1b97b097d517e546ff2d483c52f17f0083
