### ISSUE TITLE
Mod Bug - HeXeReTiC Fantasy: Keys don't open doors.

### ISSUE THREAD

**Issue by Shockwave508** [Lemon-King/HXDD#8]
When attempting to play Heretic with HXRTC Fantasy, it is impossible to progress in E1M1, the Yellow Key failing to open its respective door. 

Mod Page https://forum.zdoom.org/viewtopic.php?t=58009

**Comment by Lemon-King** [comment]
Until I get this detection fixed, you can use a workaround by typing this in the console.
`HXDD_USE_KEYDEF_MODE false`

**Comment by Lemon-King** [comment]
Fixed with: https://github.com/Lemon-King/HXDD/commit/9f3c5a47feb8e5887fb48effcc86c5c19eb2a31e
